### ISSUE TITLE
抢单用例一

### ISSUE THREAD

**Issue by pandongxia** [pandongxia/hs#17]
前提条件
1. 有两个工匠账号，A, B 一个技能：门窗修理工，锁匠，清洁工， 另一个：门窗修理工，锁匠，空调修理工

Testcase 1
预约清洁工服务

期望
A工匠收到订单，并可以抢单成功

实际结果
1. A,B都收到订单， 应该只有A收到才对 (需修改)  //2015-10-11 21:47 仍然存在
1. 需要刷新网页才可以看到提交的订单，ajax主动修改工匠页面 (需修改) //2015-10-11 21:47 仍然存在
2. A抢单成功，当B也抢单后，出现“迟了一步"的消息，此抢单并不消失，还在抢单列表内。最好消失。(需修改) //2015-10-11 21:47 仍然存在
3. 抢单成功后，点取消订单和完成订单都可以正常工作。
4. A取消订单后，B抢单并点完成订单，如果这个时候刷新A的页面，B完成的订单也会显示在A的服务过的列表中 (需查明并修改)  //2015-10-11 21:47 此问题已修复

**Comment by tracker1984** [comment]
其他的问题，我查了，没有问题，你测试时先更新下本地文件，再试试。
