### ISSUE TITLE
[10.22]注册页面需要验证用户名和邮箱唯一

### ISSUE THREAD

**Issue by pandongxia** [pandongxia/hs#2]
[优先级A]可以把用户类型放到第一个位置，这样就可以根据用户注册类型来鉴定用户名和邮箱唯一性

**Comment by tracker1984** [comment]
解决

**Comment by pandongxia** [comment]
public function checkName(){

		$where['username'] = I('username');
		$member = M('Member')->where($where)->find();
		if(empty($member)){
			$craftsman = M('craftsman')->where($where)->find();
		}
		if(empty($member)&&empty($craftsman)){
			exit('true');
		}else{
			exit('false');
		}
	}
这个函数需要区分普通用户和工匠
<div class="form-group">
                <label>用户类型</label>
                <div class="input-group"> <span class="input-group-addon"><span class="glyphicon glyphicon-asterisk"></span></span>
                	<select name="type" class="form-control" id="select">
                    	<option value="1" selected="selected">普通用户</option>
                        <option value="2">工匠</option>
                    </select>                    
                </div>
            </div>
这个放到form表单第一个位置，就可以根据用户类型进行判断唯一性。

**Comment by tracker1984** [comment]
我开始也区分了，后来感觉这个区分不好。还有用户名验证。没有人会用自己的邮箱去注册了普通的用户类型还去注册工匠的。这种几率非常小，而且显的多余。用户名如果区分，弊端就更大了。试想两个人都用一个用户名分别注册了工匠和会员，很容易混淆。建议就保持这种验证方法。如果你觉得还是要改。你QQ联系我即可。

**Comment by pandongxia** [comment]
如果不区分的话，工匠就不能预约服务了，除非他用另外的邮箱申请一个普通用户帐号。 

此问题作为遗留问题后面再解决。

**Comment by tracker1984** [comment]
已区分注册类型验证用户名和邮箱
